services:
  api:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      PORT: 5001
      DATABASE_URL: postgresql://postgres:2811@postgres:5432/taskFlowDb
      DIRECT_URL: postgresql://postgres:2811@postgres:5432/taskFlowDb
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2811
      POSTGRES_DB: taskFlowDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskFlowDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
